pragma solidity 0.5.17;

import "@openzeppelin/contracts/math/SafeMath.sol";
import "@openzeppelin/contracts/ownership/Ownable.sol";
import "@openzeppelin/contracts/utils/Address.sol";
import "../libs/DecMath.sol";
import "./MPHToken.sol";

contract MPHMinter is Ownable {
    using Address for address;
    using DecMath for uint256;
    using SafeMath for uint256;

    uint256 internal constant PRECISION = 10**18;

    /**
        @notice The multiplier applied to the interest generated by a pool when minting MPH
     */
    mapping(address => uint256) poolMintingMultiplier;
    /**
        @notice The multiplier applied to the interest generated by a pool when letting depositors keep MPH
     */
    mapping(address => uint256) poolDepositorRewardMultiplier;
    /**
        @notice The multiplier applied to the interest generated by a pool when letting deficit funders keep MPH
     */
    mapping(address => uint256) poolFunderRewardMultiplier;

    event ESetParamAddress(
        address indexed sender,
        string indexed paramName,
        address newValue
    );
    event ESetParamUint(
        address indexed sender,
        string indexed paramName,
        uint256 newValue
    );

    /**
        External contracts
     */
    MPHToken public mph;
    address public govTreasury;

    constructor(address _mph, address _govTreasury) public {
        mph = MPHToken(_mph);
        govTreasury = _govTreasury;
    }

    function mintDepositorReward(address to, uint256 interestAmount)
        external
        returns (bool)
    {
        uint256 multiplier = poolMintingMultiplier[msg.sender];
        uint256 mintAmount = interestAmount.decmul(multiplier);
        if (mintAmount == 0) {
            // sender is not a pool/has been deactivated
            return false;
        }

        mph.ownerMint(to, mintAmount);
        return true;
    }

    function mintFunderReward(address to, uint256 interestAmount)
        external
        returns (bool)
    {
        uint256 multiplier = poolMintingMultiplier[msg.sender].decmul(
            poolFunderRewardMultiplier[msg.sender]
        );
        uint256 mintAmount = interestAmount.decmul(multiplier);
        if (mintAmount == 0) {
            // sender is not a pool/has been deactivated
            return false;
        }

        mph.ownerMint(to, mintAmount);
        return true;
    }

    function takeBackDepositorReward(address from, uint256 interestAmount)
        external
        returns (bool)
    {
        uint256 multiplier = poolMintingMultiplier[msg.sender].decmul(
            PRECISION.sub(poolDepositorRewardMultiplier[msg.sender])
        );
        uint256 takeBackAmount = interestAmount.decmul(multiplier);
        if (takeBackAmount == 0) {
            // sender is not a pool/has been deactivated
            return false;
        }

        mph.ownerTransfer(from, govTreasury, takeBackAmount);
        return true;
    }

    /**
        Param setters
     */
    function setGovTreasury(address newValue) external onlyOwner {
        require(newValue != address(0), "MPHMinter: 0 address");
        govTreasury = newValue;
        emit ESetParamAddress(msg.sender, "govTreasury", newValue);
    }

    function setPoolMintingMultiplier(address pool, uint256 newMultiplier)
        external
        onlyOwner
    {
        require(pool.isContract(), "MPHMinter: pool not contract");
        poolMintingMultiplier[pool] = newMultiplier;
        emit ESetParamUint(msg.sender, "poolMintingMultiplier", newMultiplier);
    }

    function setPoolDepositorRewardMultiplier(
        address pool,
        uint256 newMultiplier
    ) external onlyOwner {
        require(pool.isContract(), "MPHMinter: pool not contract");
        require(newMultiplier <= PRECISION, "MPHMinter: invalid multiplier");
        poolDepositorRewardMultiplier[pool] = newMultiplier;
        emit ESetParamUint(
            msg.sender,
            "poolDepositorRewardMultiplier",
            newMultiplier
        );
    }

    function setPoolFunderRewardMultiplier(address pool, uint256 newMultiplier)
        external
        onlyOwner
    {
        require(pool.isContract(), "MPHMinter: pool not contract");
        poolFunderRewardMultiplier[pool] = newMultiplier;
        emit ESetParamUint(
            msg.sender,
            "poolFunderRewardMultiplier",
            newMultiplier
        );
    }
}
